<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Iot.Device.Bmp581</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Device.gpio" Version="4.0.1" />
    <PackageReference Include="UnitsNet" Version="5.74.0" />
  </ItemGroup>

</Project>
